# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from openerp.osv import fields, osv


#se declar las clase y sus atributos 
class cesta_ticket(osv.osv):
    
    _name="cesta.cesta_ticket"
    _rec_name="ut"
   
    def funcion_cal_cesta_ticket(self,cr,uid,ids,field_name,arg,context=None):
            res={}
            for r in self.browse(cr,uid,ids):
                res[r.id]=r.ut*r.put
            return res 
        
        
    _columns={
        'ut':fields.float('Cantidad Unidad Tributaria', digits=(16,2),required=True,help='Unidad Tributaria Actual'),
        'put':fields.float('Punto Unidad Tributaria', digits=(16,2),required=True,help='Punto Unidad Tributaria Actual'),
        'precio_venta': fields.function(
                            funcion_cal_cesta_ticket, 
                            'Precio Venta', store=True,
                            type='float'),
        # 'cedula':fields.integer('Cedula',size=10,required=True,help='Esta es la Cedula de hola mundo'),
        # 'sexo':fields.selection([('masculino','Masculino'),('femenino','Femenino')],'sexo',help='seleccionar sexo', required=True),
    }
    
    
    
         
            
    
    
    
